import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppBar from "./components/AppBar";
import ThemeProvider from "./themeProvider";
import ClientProvider from "./ClientProvider";
import { ToastContainer } from "react-toastify";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hotel management system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
       <ClientProvider>
        <ToastContainer autoClose={2000} />
       <AppBar/>
       {children}
       </ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
